### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by infernix** [GrandadEvans/dual-timer#1]
It seems that the GUI was dropped and not yet reimplemented since dc321aef11d60c9d8190abb92d1155e8f92052ba - are you running this in some undocumented way? Maybe forgot to commit some files? Or am I missing something here?

**Comment by GrandadEvans** [comment]
Hi Infernix, unfortunately this is a project that I had to shelve for the time being but I do hope to go back to it in a few months.

To be honest I can't remember why I dropped the GUI off-hand. I'm sure it was just meant to be a temp. measure though.

Sorry for the delay in replying. A long term health issue is unfortunately keeping me from work and my personal projects at the minute...and I'm just not the best at spotting real emails these days :-/

John

**Comment by infernix** [comment]
Thanks for the heads up. Feel free to ping me if you do get around to picking this up in the future. Best of luck :)
